anvil-python/anvil/main.py

Closes #4. There is a small typo in the help text. This change removes an extra word.

Fix a small typo in the help text

---

.github/workflows/build-snap.yml
anvil-python/anvil/commands/prepare_node.py

This PR simplifies the initialization process of Anvil by including the commands that wire Juju into the `prepare-node-script`.

feat: extend prepare-node-script to include Juju wiring

---

README.md
anvil-python/README.md

Add basic documentation for a three-node MAAS deployment with Anvil

docs: add three-node deployment notes

---

anvil-python/anvil/commands/inspect.py
anvil-python/anvil/commands/manifest.py
anvil-python/anvil/jobs/checks.py
anvil-python/anvil/main.py
anvil-python/anvil/provider/local/commands.py

This PR includes the following:
- removal of `cluster resize` command which does not apply to `maas-anvil`
- update on checks' messages to mention `maas-anvil` instead of `sunbeam`
**NOTE:** The microcluster that maas-anvil is using is the sunbeam microcluster. The references to it as `sunbeam` will remain since otherwise a huge refactor of common functions between sunbeam and anvil is required. There is not a huge benefit to do so. In addition, the sunbeam microcluster is used as a whole, without any modification.

bug: remove sunbeam leftovers

---

anvil-python/anvil/commands/haproxy.py
anvil-python/anvil/commands/maas_agent.py
anvil-python/anvil/commands/maas_region.py
anvil-python/anvil/commands/postgresql.py
anvil-python/anvil/provider/local/commands.py

This PR includes the following:
- a fix for new nodes that are joining the anvil cluster. Instead of running only the add unit steps of each role, anvil has to also run the terraform init and install application steps. Otherwise, if a new node wants to join with a role that bootstrap node does not have, the usage of only the add unit step fails. At this point, the terraform plan of the role has not been initialized yet and the charmed application has not been installed
- an overall refactor of bootstrap and join commands to make them more comprehensible

fix: allow node roles different than bootstrapped node

---

anvil-python/anvil/versions.py
cloud/etc/deploy-maas-agent/main.tf
cloud/etc/deploy-maas-region/main.tf
cloud/etc/deploy-maas-region/variables.tf

This PR adds pgbouncer charm as a subordinate charm of maas-region. Instead of directly communicating with PostgreSQL, MAAS region will use pgbouncer as a proxy. The number of max connections to pgbouncer is configured as relevant to the number of MAAS region nodes of Anvil cluster.
This PR is an enabler for fixing: #11, if not a complete fix at all. In case the default sane values that this PR uses are not enough to fix the starvation issue, the way pgbouncer is introduced, provides a way to override their values. Those overridden values can be passed to pgbouncer through the `manifest` mechanism of maas-anvil.

feat: introduce pgbouncer as a PostgreSQL proxy

---

README.md

we have the keepalived charm there, why not PgBouncer?

chore: add PgBouncer link to README

---

README.md
anvil-python/anvil/commands/maas_agent.py
anvil-python/anvil/commands/maas_region.py
anvil-python/anvil/commands/postgresql.py
anvil-python/anvil/provider/local/commands.py
anvil-python/anvil/provider/local/deployment.py
anvil-python/anvil/versions.py
cloud/etc/deploy-maas-region/main.tf
cloud/etc/deploy-maas-region/variables.tf
cloud/etc/deploy-postgresql/main.tf
cloud/etc/deploy-postgresql/variables.tf

The PR includes the following changes:
- Set PgBouncer `pool_mode` to `session` since `pg_advisory_lock` cannot be supported by `transaction` mode
- Set a predefined number for the maximum connections to the database server from each PgBouncer unit to be 50. Those are the maximum connections that MAAS up to 3.4 requires per region controller (40), plus a buffer of 10. PgBouncer units are subordinate units of `maas-region` units, so it has to be a 1-1 mapping. The extra 10, if not used they will be closed by PgBouncer.
- Provide a mechanism to configure `experimental_max_connections` to PostgreSQL charm with three options:
- `default`: It does not set `experimental_max_connections` at all. It will use the system defaults of PostgreSQL
- `dynamic`: It configures …

bug: configure maximum db connections

---

anvil-python/anvil/commands/juju.py
anvil-python/anvil/jobs/checks.py
anvil-python/anvil/provider/local/commands.py

Uses `juju add-ssh-key` to add the node's public key to the model, allowing users to ssh to each machine with `juju ssh`

feat: Add node's ssh key to Juju model on join

---

anvil-python/anvil/commands/haproxy.py
anvil-python/anvil/commands/juju.py
anvil-python/anvil/commands/maas_agent.py
anvil-python/anvil/commands/maas_region.py
anvil-python/anvil/commands/postgresql.py
anvil-python/anvil/jobs/steps.py
anvil-python/anvil/provider/local/commands.py

- Extend Sunbeam `RemoveMachineUnitStep` and `RemoveJujuMachineStep` so that maas-anvil is properly waiting for the removal of units and machines.
- For `RemoveJujuMachineStep` an extra check is added to ensure that if an error is received during removal, this error is not about the non-existence of the machine. A machine without any units deployed on it is auto-removed. As such, the moment when the command runs, the machine can be already removed.
- Re-order the removal of units of Juju applications of Anvil roles to happen in reverse order of their addition.

bug: properly wait for removal of units and machines

---

README.md
anvil-python/anvil/commands/haproxy.py
anvil-python/anvil/commands/maas_agent.py
anvil-python/anvil/commands/maas_region.py
anvil-python/anvil/commands/postgresql.py
anvil-python/anvil/commands/refresh.py
anvil-python/anvil/commands/upgrades/base.py
anvil-python/anvil/commands/upgrades/intra_channel.py
anvil-python/anvil/main.py
anvil-python/pyproject.toml
cloud/etc/deploy-haproxy/main.tf

- Introduce the command `maas-anvil refresh` to refresh the configuration of the cluster from a manifest.
Addresses MAASENG-3304

feat: Add cluster refresh

---

anvil-python/anvil/versions.py
cloud/etc/deploy-maas-region/variables.tf

- Switches the default channel of Postgresql to 14/stable: rev. 429 is now on 14/stable
- Switches the default channel of Pgbouncer to 1/stable: rev. 278 is now on 1/stable
Resolved GH: https://github.com/canonical/maas-anvil/issues/41

chore(deps): switch to stable channels for PostgreSQL/PgBouncer

---

anvil-python/anvil/commands/clusterd.py
anvil-python/anvil/provider/local/commands.py

- add an intermediate class for cluster operations that replaces "sunbeam" in console logs with "anvil"

refactor: remove sunbeam from console

---

anvil-python/anvil/provider/local/commands.py

After a successful bootstrap, set the appropriate config key to the microcluster database. Both `maas-anvil` and `sunbeam` are depending on it.
Resolves GH: #51

fix: set bootstrapped flag

---

anvil-python/anvil/commands/haproxy.py
anvil-python/anvil/commands/postgresql.py

Do not display a prompt to the user If the step contains questions but will be skipped.

fix: do not ask question on skipped steps

---

anvil-python/anvil/commands/haproxy.py
anvil-python/anvil/jobs/questions.py
anvil-python/anvil/provider/local/deployment.py

- Add an string as the default value instead of empty YAML value, when default value is the empty string
- Modify haproxy SSL questions to default to empty string
- Update question bank variable name from keepalived to haproxy when generating a manifest
- Modify vip question validator to retun None or raise ValueError
resolves: #58

fix: manifest with empty default values

---

README.md
anvil-python/anvil/commands/manifest.py
anvil-python/anvil/commands/refresh.py
anvil-python/anvil/jobs/manifest.py
anvil-python/anvil/provider/local/commands.py

- Accept stdin as manifest file by setting `click.Path.allow_dash` to True
- open manifest file with `click.open_file()` which can handle dash appropriately
- Implement maas-anvil version of `AddManifestStep` to use `manifest_data`
- Update README
- Fix typos
resolves: #55

feat: read manifest from stdin

---

anvil-python/anvil/commands/manifest.py
anvil-python/anvil/provider/local/commands.py

Changes the `--name` flag to `--fqdn` for commands `maas-anvil cluster add` and `maas-anvil cluster remove`, and changes the `--manifest-file` flag to `--output` for `maas-anvil manifest generate`.
Addresses https://github.com/canonical/maas-anvil/issues/72

fix: rename --name and --manifest-file flags to be more explicit

---

anvil-python/anvil/commands/haproxy.py
anvil-python/anvil/commands/maas_region.py
anvil-python/anvil/commands/upgrades/intra_channel.py
anvil-python/anvil/provider/local/commands.py
anvil-python/anvil/provider/local/deployment.py
anvil-python/anvil/versions.py
cloud/etc/deploy-maas-region/main.tf
cloud/etc/deploy-maas-region/variables.tf

Adds configuration for passing encrypted requests through HAProxy, to MAAS. 
Requires merging of https://github.com/canonical/maas-charms/pull/220. Until it is merged, you can use `latest/edge/passthrough-test` for the maas-region charm channel

feat: TLS passthrough

---

cloud/etc/deploy-haproxy/main.tf
cloud/etc/deploy-haproxy/variables.tf
cloud/etc/deploy-maas-agent/main.tf
cloud/etc/deploy-maas-region/main.tf
cloud/etc/deploy-postgresql/main.tf

Fixes https://github.com/canonical/maas-anvil/issues/80 and https://github.com/canonical/maas-anvil/issues/79
* Updates the Juju Terraform provider to 0.15.1
* Switches the haproxy channel to latest/stable
Bootstrapped a node locally as a test and the charms idled.

fix: update TF provider and switch haproxy stable channel

---

README.md
anvil-python/anvil/commands/inspect.py
anvil-python/anvil/commands/manifest.py
anvil-python/anvil/commands/prepare_node.py
anvil-python/anvil/commands/refresh.py
anvil-python/anvil/commands/utils.py
anvil-python/anvil/main.py
anvil-python/anvil/provider/local/commands.py
anvil-python/anvil/utils.py

Updates the documentation in the README file. To see a rendered version of the changed markdown [see the README in my fork](https://github.com/dgtlntv/maas-anvil?tab=readme-ov-file).
[Related Jira epic](https://warthogs.atlassian.net/browse/MAASENG-3190)

docs: update maas-anvil documentation

---

anvil-python/anvil/commands/haproxy.py
anvil-python/anvil/commands/maas_agent.py
anvil-python/anvil/commands/maas_region.py
anvil-python/anvil/commands/postgresql.py
anvil-python/anvil/commands/upgrades/inter_channel.py
anvil-python/anvil/commands/upgrades/intra_channel.py

addresses the following points raised in #61:
- Blindly adding charms, rather than checking at least one node has the role for that charm
- Log messages containing "deploy" rather than "refresh"
Still requires modification to handle detecting deployment manifest changes before saving to the database.
May cause merge conflicts with #65

refactor: fix known issues in refresh command

---

README.md
anvil-python/anvil/commands/utils.py
anvil-python/anvil/main.py
anvil-python/anvil/utils.py

Adds two commands which are forwarded to the `maas-region` charm via `juju run`: `create-admin` and `get-api-key`

feat: add create-admin and get-api-key commands

---

cloud/etc/deploy-postgresql/main.tf

Until a proper fix is released for https://bugs.launchpad.net/maas/+bug/2097079 and after the postgresql revision 553 was released to 14/stable, we need to start the postgresql with the pgaudit plugin set to disabled.

fix: workaround for LP-2097079

---

.github/workflows/build-snap.yml
.github/workflows/test-python.yml
anvil-python/anvil/commands/prepare_node.py
anvil-python/anvil/commands/refresh.py
anvil-python/anvil/provider/local/commands.py
anvil-python/pyproject.toml
anvil-python/requirements.txt

- Bump Juju to 3.6 LTS
- Use a branch of `snap-openstack`, which is a modified version of tag `anvil-0.1`, that uses a bumped Juju python lib to 3.6
- Update Python dependencies to pin to versions related to Juju python lib 3.6
- Pin GH runners to jammy since `ubuntu-latest` is pointing to Noble now, it is using a newer Python and it is breaking pip installation due to different dependency versions

chore: upgrade Juju to 3.6 LTS

---

anvil-python/anvil/provider/local/commands.py

addresses #68 
If a manifest is passed, we force accept_defaults to True, preventing it asking questions. This should result in the manifest configuration being used, or the default values if the value is not present in the manifest.

feat: accept defaults for non manifest parameters when a manifest is passed

---

.github/workflows/build-snap.yml
anvil-python/anvil/commands/haproxy.py
anvil-python/anvil/commands/maas_agent.py
anvil-python/anvil/commands/maas_region.py
anvil-python/anvil/commands/postgresql.py
anvil-python/anvil/utils.py
cloud/etc/deploy-haproxy/main.tf
cloud/etc/deploy-haproxy/variables.tf
cloud/etc/deploy-maas-agent/main.tf
cloud/etc/deploy-maas-agent/variables.tf
cloud/etc/deploy-maas-region/main.tf
cloud/etc/deploy-maas-region/variables.tf
cloud/etc/deploy-postgresql/main.tf
cloud/etc/deploy-postgresql/variables.tf

- Enable maas-anvil functional tests against arm64 runners
- Add a function to detect the architecture of the MAAS node to be provided as a constraint to Juju. Juju cannot automatically install the charm for the proper architecture.
- Pass detected architecture to Juju Terraform plans

chore: maas-anvil on arm64

---

anvil-python/anvil/versions.py
cloud/etc/deploy-maas-region/main.tf
cloud/etc/deploy-maas-region/variables.tf
cloud/etc/deploy-postgresql/main.tf

- Adds a new integration for MAAS-region with the S3-integrator charm.
A new unit with it's own configuration set is co-located with the MAAS-region, rather than re-using the PostgreSQL S3-integrator unit.
Requires the newest revision of the MAAS region charm that includes the relation, which is currently unreleased

feat: Introduce s3 relation for MAAS-region
